### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by froggz19** [wr1ght/kodicord#5]
Spawning RPC process...
url.js:154
    throw new ERR_INVALID_A
RG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at urlParse (url.js:148:13)
    at new KodiRequest (C:\Users\George\Desktop\kodicord-master\kodicord-master\src\modules\KodiRequest.js:6:30)
    at new Core (C:\Users\George\Desktop\kodicord-master\kodicord-master\src\core\Core.js:12:28)
    at Object.<anonymous> (C:\Users\George\Desktop\kodicord-master\kodicord-master\src\core\index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

Song changed, restarting RPC process.
Spawning RPC process...
url.js:154
    throw new ERR_INVALID_ARG_TYPE('
url', 'string', url);
    ^

**Comment by froggz19** [comment]
my bad, forgot to rename the .env
